openapi: 3.0.0
servers:
- url: http://localhost:8080
info:
  version: 0.0.1
  title: Millom API rich notification-based API for service providers
  description: >-
    Rich notification API allows service providers to fetch offers
    if their APIs are not zero-rated even in the cases when the user
    is completely out of data.

paths:
  /notification/path/defined/by/service/provider:
    post:
      tags:
        - Implemented by service provider
      summary: Service provider rich notifications receiving API
      description: >
        Millom sends rich notification to this endpoint 
        implemented by the service provider.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - title: cpid
                  type: object
                  properties:
                    cpid:
                      type: string
                      description: CPID — volatile user identifier
                      example: '0uZmrnhbJa5YMBHuuVUQ+6nCWMoCZusDLNho3dkrt62XKlIQ582BkYBaz5yKKPdE+U/3ezNMWtIecmkxRUFjRmxNODNN,51001'
                - $ref: "#/components/schemas/RefreshableOffers"

      responses:
        200:
          description: Notification is accepted for delivery
        500:
          description: Internal server error
        503:
          description: Service unavailable
        400:
          description: Bad request
      security:
        - serviceProviderAuthentication:
            - any

  /rnf/{serviceProvider}/{operator}/{cpid}/offers:
    get:
      summary: Refresh offers via signed link
      description: |
        Fetch updated offers via a signed link that was provided in other channel
        (for example, in a rich notification request).
        
        Works even if the user is out of data, since it points to a zero-rated endpoint.
      tags:
        - Provided by Millom
      parameters:
        - $ref: "#/components/parameters/serviceProvider"
        - $ref: "#/components/parameters/operator"
        - $ref: "#/components/parameters/cpid"
        - $ref: "#/components/parameters/uuid"
        - $ref: "#/components/parameters/expirySeconds"
        - $ref: "#/components/parameters/signature"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshableOffers"
        401:
          description: Unauthorized
        500:
          description: Internal server error
        503:
          description: Service unavailable
        400:
          description: Bad request

  /rnf/{serviceProvider}/{operator}/{cpid}/ping:
    get:
      summary: Check network connectivity
      description: |
        Check network connectivity to detect when mobile users are out of data,
        but still have coverage.
        
        Works even if the user is out of data, since it points to a zero-rated endpoint.
      tags:
        - Provided by Millom
      parameters:
        - $ref: "#/components/parameters/serviceProvider"
        - $ref: "#/components/parameters/operator"
        - $ref: "#/components/parameters/cpid"
        - $ref: "#/components/parameters/uuid"
        - $ref: "#/components/parameters/expirySeconds"
        - $ref: "#/components/parameters/signature"
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        500:
          description: Internal server error
        503:
          description: Service unavailable
        400:
          description: Bad request

  /rnf/{serviceProvider}/{operator}/{cpid}/purchasePlan:
    get:
      summary: Initiate purchase
      description: |
        Initiate purchase of a product using purchase link provided in the offers list.
        
        Works even if the user is out of data, since it points to a zero-rated endpoint.
      tags:
        - Provided by Millom
      parameters:
        - $ref: "#/components/parameters/serviceProvider"
        - $ref: "#/components/parameters/operator"
        - $ref: "#/components/parameters/cpid"
        - $ref: "#/components/parameters/uuid"
        - $ref: "#/components/parameters/expirySeconds"
        - $ref: "#/components/parameters/signature"
        - name: fundSource
          in: query
          description: Identifies source of funds for this activation
          schema:
            $ref: "#/components/schemas/FundSource"
        - name: planId
          in: query
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          required: true
          schema:
            type: string
        - name: Accept-Language
          in: header
          schema:
            type: string

      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        500:
          description: Internal server error
        503:
          description: Service unavailable
        400:
          description: Bad request
  /callback/path/defined/by/service/provider/:
    post:
      summary: "Purchase callback"
      description: "This is an async callback with a result of a plan activation attempt"
      requestBody:
        content:
          application/json:
            schema:
              required:
                - "transactionId"
                - "appId"
              type: "object"
              properties:
                transactionId:
                  type: "string"
                  description: "Identifier of a transaction, the same as the purchase transactionId"
                message:
                  type: "string"
                  description: "Can be anything. Generic purpose field, used to pass any information"
                appId:
                  type: "string"
                  description: "Identifier of the Service Provider"
                  example: "facebook"
                  enum:
                    - "google"
                    - "facebook"
                    - "facebook-cp"
                    - "tiktok"
                errorType:
                  $ref: '../../operators/purchase-callback/millom-callback.yaml#/components/schemas/ErrorType'
                errorCode:
                  type: "string"
                  example: "400.70.2"
                  description: "Any error code to provide more insight into the problem, if required"
                dryRun:
                  type: "boolean"
                  description: "a dry run. true - it's not going to be processed, only an OK response is going to be returned. false - callback is going to be processed. "
                redirectLink:
                  type: "string"
                  description: "A redirect link to which the webview should redirect to (if applicable)"
                  example: "http://someredirectlink.com/user/id"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad request. (missing mandatory query parameters or malformed\
            \ body)"
        "404":
          description: "Not found. (Transaction not found in cache)"
        "500":
          description: "Server Internal error"


components:
  securitySchemes:
    serviceProviderAuthentication:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://provided.by.service.provider"
          scopes:
            any: allows incoming rich notifications
  schemas:
    Offer:
      type: object
      properties:
        planId:
          type: string
          description: Unique ID for this offered plan
        cost:
          type: string
          description: Cost of this offer, as a quoted decimal number.
          format: currency
          example: "14"
        costCurrency:
          type: string
          description: ISO 4217 code for the currency of the cost.
        type:
          type: string
          description: Description of the type of dataplan this is.
          example: "Data"
        planName:
          type: array
          items:
            $ref: "#/components/schemas/MultilingualText"
        planDescription:
          type: array
          items:
            $ref: "#/components/schemas/MultilingualText"
        quota:
          description: The initial size of this plan, in bytes, minutes etc
          type: array
          items:
            type: object
            properties:
              unit:
                type: string
                enum: ["bytes", "data-minutes", "voice-minutes", "sms"]
                example: "bytes"
              quota:
                type: number
                example: 1073741824
                description: >
                  The value of the initial size, in the given unit.
                  Unlimited plans are expressed with a byte quota value of 2^63 - 1 (9223372036854775807).
        offerContext:
          type: string
          description: random text string with offer cookie data. \
            If present, it must be provided in activation request.
        fundSource:
          allOf:
            - $ref: "#/components/schemas/FundSource"
            - description: Identifies source of funds that can be used to purchase this plan

        paymentUri:
          type: string
          description: > 
            A link initiate purchase with e-wallet payment directly from end-user device.
            Works even if the user is out of data, since it points to a zero-rated endpoint.
          example: https://millom.static.api/v1/ewallet/myspace/mycomm/7%2FC8NpcqRiX3rja4JslR83FtKXHSJnMgXJOXZ%2FawPWIge8WFcBt0CpmbXJVkac2f53GGjYqeGjlGjuiE1bKYJhh9J0t3dIK6iXnN7g0Fxnjv0rTV1XvgB95GN0folvrxG42GnPSYL21oLVSUrgdA8BJBdZZFW082ebg%2B%2Bn5dRsMJs96jFqD1o8rzoYq1rDh15o1Lgfe%2BEPIb6zk7FjYs3OLOSpkqo7hQZkg2UXI1OXNYcWg%3D%2C47001??planId=SOMETHING2GB&planName=Freedom+Apps+IG+%26+FB+2GB+%2F+1+Hari&planDescription=Freedom+Apps+Facebook+%26+Instagram+2GB+%2F+1+Hari.+Kuota+hanya+dapat+digunakan+untuk+Someapp+%26+Someotherapp.+Penggunaan+aplikasi+lain+akan+menggunakan+pulsa+atau+kuota+lainnya&planPrice=5000.00&planCurrency=IDR&transactionId=cc15abad-30cc-4e84-85bb-c4c28ddaddde&uuid=bbe5531d-0680-4632-a2ab-ff91e7e69f24&expirySeconds=1694515016&signature=5pmfikymoIJdEzjjMZoIVX1_BdbwGhBqpsfFNUVwr3c%3D
        purchaseLink:
          type: string
          description: >
            A link initiate purchase with e-wallet payment directly from end-user device.
            Works even if the user is out of data, since it points to a zero-rated endpoint.
          example: https://millom.static.api/v1/ewallet/myspace/mycomm/7%2FC8NpcqRiX3rja4JslR83FtKXHSJnMgXJOXZ%2FawPWIge8WFcBt0CpmbXJVkac2f53GGjYqeGjlGjuiE1bKYJhh9J0t3dIK6iXnN7g0Fxnjv0rTV1XvgB95GN0folvrxG42GnPSYL21oLVSUrgdA8BJBdZZFW082ebg%2B%2Bn5dRsMJs96jFqD1o8rzoYq1rDh15o1Lgfe%2BEPIb6zk7FjYs3OLOSpkqo7hQZkg2UXI1OXNYcWg%3D%2C47001??planId=SOMETHING2GB&transactionId=cc15abad-30cc-4e84-85bb-c4c28ddaddde&uuid=bbe5531d-0680-4632-a2ab-ff91e7e69f24&expirySeconds=1694515016&signature=5pmfikymoIJdEzjjMZoIVX1_BdbwGhBqpsfFNUVwr3c%3D
    MultilingualText:
      type: object
      properties:
        language:
          type: string
          description: What language the 'text' field is expressed as. BCP-47 language code
          example: "en-us"
        text:
          type: string
          description: Textual description of this offer, for humans to read.
          example: "Super plan, 10 GB data valid for a week"
    RefreshableOffers:
      type: object
      properties:
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"
        refresh:
          type: string
          description: >
            A link _end-user client_ uses to fetch most recent offers 
            (the endpoint is typically zero-rated). 
            
            Can be used directly with a `GET` request.
          example: "https://millom.static.api/myspace/mycomm/7%2FC8NpcqRiX3rja4JslR83FtKXHSJnMgXJOXZ%2FawPWIge8WFcBt0CpmbXJVkac2f53GGjYqeGjlGjuiE1bKYJhh9J0t3dIK6iXnN7g0Fxnjv0rTV1XvgB95GN0folvrxG42GnPSYL21oLVSUrgdA8BJBdZZFW082ebg%2B%2Bn5dRsMJs96jFqD1o8rzoYq1rDh15o1Lgfe%2BEPIb6zk7FjYs3OLOSpkqo7hQZkg2UXI1OXNYcWg%3D%2C47001/offers?uuid=bbe5531d-0680-4632-a2ab-ff91e7e69f24&expirySeconds=1694515016&signature=5pmfikymoIJdEzjjMZoIVX1_BdbwGhBqpsfFNUVwr3c%3D"
        ping:
          type: string
          description: >
            A link _end-user client_ uses to check if current connection 
            issue is due to lack of data or missing coverage
            (the endpoint is typically zero-rated)
            
            Can be used directly with a `GET` request.
          example: "https://millom.static.api/myspace/mycomm/7%2FC8NpcqRiX3rja4JslR83FtKXHSJnMgXJOXZ%2FawPWIge8WFcBt0CpmbXJVkac2f53GGjYqeGjlGjuiE1bKYJhh9J0t3dIK6iXnN7g0Fxnjv0rTV1XvgB95GN0folvrxG42GnPSYL21oLVSUrgdA8BJBdZZFW082ebg%2B%2Bn5dRsMJs96jFqD1o8rzoYq1rDh15o1Lgfe%2BEPIb6zk7FjYs3OLOSpkqo7hQZkg2UXI1OXNYcWg%3D%2C47001/ping?uuid=bbe5531d-0680-4632-a2ab-ff91e7e69f24&expirySeconds=1694515016&signature=5pmfikymoIJdEzjjMZoIVX1_BdbwGhBqpsfFNUVwr3c%3D"
        shop:
          type: string
          description: >
            A link _end-user client_ uses to open web-based Millom shop 
            
            Can be user in a webview or extermal browser.
          example: "https://millom.static.api/myspace/mycomm/7%2FC8NpcqRiX3rja4JslR83FtKXHSJnMgXJOXZ%2FawPWIge8WFcBt0CpmbXJVkac2f53GGjYqeGjlGjuiE1bKYJhh9J0t3dIK6iXnN7g0Fxnjv0rTV1XvgB95GN0folvrxG42GnPSYL21oLVSUrgdA8BJBdZZFW082ebg%2B%2Bn5dRsMJs96jFqD1o8rzoYq1rDh15o1Lgfe%2BEPIb6zk7FjYs3OLOSpkqo7hQZkg2UXI1OXNYcWg%3D%2C47001?uuid=bbe5531d-0680-4632-a2ab-ff91e7e69f24&expirySeconds=1694515016&signature=5pmfikymoIJdEzjjMZoIVX1_BdbwGhBqpsfFNUVwr3c%3D"
    FundSource:
      type: string
      enum:
        - WALLET
        - EWALLET
        - LOAN
        - FREE
  parameters:
    serviceProvider:
      name: serviceProvider
      required: true
      in: path
      description: Agreed service provider identifier to access the millom platform
      schema:
        type: string
    operator:
      name: operator
      required: true
      in: path
      description: Operator name
      schema:
        type: string
    cpid:
      name: cpid
      required: true
      in: path
      description: Subscriber identifier
      schema:
        type: string
    uuid:
      name: uuid
      in: query
      required: true
      schema:
        type: string
    expirySeconds:
      name: expirySeconds
      in: query
      required: true
      schema:
        type: string
        format: date
    signature:
      name: signature
      in: query
      required: true
      schema:
        type: string
